server:
  port: 8081

kvstore:
  cluster:
    nodeName: node1
    nodeRole: PRIMARY
    discoveryEndpoints: http://node2:8082,http://node3:8083
    replicationFactor: 3
    readQuorum: 2
    writeQuorum: 2
    requestTimeoutMs: 3000
  storage:
    type: memory
    dataDirectory: /app/data
