server:
  port: 8083

kvstore:
  cluster:
    nodeName: node3
    nodeRole: PRIMARY
    discoveryEndpoints: http://node1:8081,http://node2:8082
    replicationFactor: 3
    readQuorum: 2
    writeQuorum: 2
    requestTimeoutMs: 3000
  storage:
    type: memory
    dataDirectory: /app/data
    maxSizeInMb: 1024
    compactionIntervalMinutes: 60
