version: "3.1"
services:
    mysql:
        image: mysql:latest
        container_name: stream-test
        ports:
            - "3307:3306"
        volumes:
            - ~/docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:ro
            - ~/docker/mysql/var/lib/mysql:/var/lib/mysql
            - ~/docker/mysql/var/log/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=stream-test
        command: --default-authentication-plugin=mysql_native_password
        restart: always
