// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int32              `db:"id" json:"id"`
	PostID    int32              `db:"post_id" json:"post_id"`
	Content   string             `db:"content" json:"content"`
	Author    string             `db:"author" json:"author"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Post struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Content   pgtype.Text        `db:"content" json:"content"`
	Author    string             `db:"author" json:"author"`
	ViewCount pgtype.Int4        `db:"view_count" json:"view_count"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
