// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, id int64) error
	// 게시글 관련 쿼리 정의
	// Spring Data JPA의 @Query와 유사하지만 더 명시적
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error)
	GetPostsCount(ctx context.Context) (int64, error)
	IncrementViewCount(ctx context.Context, id int64) (pgtype.Int4, error)
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
