// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// 사용자 수 조회
	CountUsers(ctx context.Context) (int64, error)
	// 사용자 생성 (MySQL의 LAST_INSERT_ID() 활용)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	// 사용자 삭제
	DeleteUser(ctx context.Context, id int64) error
	// SQLC가 자동으로 Go 코드를 생성할 SQL 쿼리들
	// 모든 사용자 조회 (Java의 @Select와 유사하지만 타입 안전성 보장)
	GetAllUsers(ctx context.Context) ([]*User, error)
	// 이메일로 사용자 조회
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	// ID로 사용자 조회 (존재하지 않으면 sql.ErrNoRows 반환)
	GetUserByID(ctx context.Context, id int64) (*User, error)
	// 페이지네이션 지원 사용자 목록
	GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]*User, error)
	// 사용자 정보 업데이트
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	// 부분 업데이트 (NULL 체크 포함)
	UpdateUserPartial(ctx context.Context, arg UpdateUserPartialParams) error
}

var _ Querier = (*Queries)(nil)
